---
- name: Setup yum repositories for all hosts
  hosts: oo_all_hosts
  gather_facts: no
  tasks:
  - name: subscribe instances to Red Hat Subscription Manager
    include_role:
      name: rhel_subscribe
    when:
    - ansible_distribution == 'RedHat'
    - deployment_type == 'openshift-enterprise'
    - (rhel_subscription_user or rhsub_user) is defined
    - (rhel_subscription_password or rhsub_pass) is defined
  - name: initialize openshift repos
    include_role:
      name: openshift_repos
