---
# input variables:
# - openshift_service_type
# - openshift.common.is_containerized
# - docker_version
# - skip_docker_restart

- name: Check Docker image count
  shell: "docker images -aq | wc -l"
  register: docker_image_count

- debug: var=docker_image_count.stdout

- service:
    name: docker
    state: stopped
  register: l_openshift_node_upgrade_docker_stop_result
  until: not l_openshift_node_upgrade_docker_stop_result | failed
  retries: 3
  delay: 30

- name: Upgrade Docker
  package: name=docker{{ '-' + docker_version }} state=present
  register: result
  until: result | success

# starting docker happens back in ../main.yml where it calls ../restart.yml
